
import type { Product, Category } from '@/types';
// Lucide icons are now primarily managed by iconMap.tsx for categories from API
// Keeping direct imports if other mock data sections might use them, or for fallback type safety.
// import { Rocket, Bomb, Sparkles, Disc3, Gift, Smile } from 'lucide-react';

export const categories: Category[] = [
  { 
    id: 'sky-shots', 
    name: 'Sky Shots / Aerials', 
    slug: 'sky-shots', 
    imageUrl: 'https://placehold.co/200x150.png', 
    imageHint: 'sky fireworks',
    displayOrder: 1
  },
  { 
    id: 'ground-crackers', 
    name: 'Ground Crackers', 
    slug: 'ground-crackers', 
    imageUrl: 'https://placehold.co/200x150.png', 
    imageHint: 'ground firecrackers',
    displayOrder: 2
  },
  { 
    id: 'sparklers', 
    name: 'Sparklers', 
    slug: 'sparklers', 
    imageUrl: 'https://placehold.co/200x150.png', 
    imageHint: 'handheld sparklers',
    displayOrder: 3
  },
  { 
    id: 'spinning-crackers', 
    name: 'Spinning Crackers', 
    slug: 'spinning-crackers', 
    imageUrl: 'https://placehold.co/200x150.png', 
    imageHint: 'spinning fireworks',
    displayOrder: 4
  },
  { 
    id: 'fancy-novelty', 
    name: 'Fancy / Novelty', 
    slug: 'fancy-novelty', 
    imageUrl: 'https://placehold.co/200x150.png', 
    imageHint: 'festive fireworks',
    displayOrder: 5
  },
  { 
    id: 'kids-special', 
    name: 'Kids Special', 
    slug: 'kids-special', 
    imageUrl: 'https://placehold.co/200x150.png', 
    imageHint: 'safe fireworks',
    displayOrder: 6
  },
];

export const products: Product[] = [
  // Sky Shots / Aerials
  {
    id: 'sky_7_shots_peacock',
    name: '7 Shots Peacock',
    description: 'Aerial shots displaying a beautiful peacock feather pattern.',
    price: 19.99,
    category: 'Sky Shots / Aerials',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'peacock fireworks',
    rating: 4.6,
    stock: 30,
  },
  {
    id: 'sky_3_sound_rocket',
    name: '3 Sound Rocket',
    description: 'Rocket that emits three distinct sound effects as it soars.',
    price: 9.50,
    category: 'Sky Shots / Aerials',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'sound rocket',
    rating: 4.3,
    stock: 60,
  },
  {
    id: 'sky_fancy_rocket',
    name: 'Fancy Rocket',
    description: 'A rocket with unique visual effects and colors.',
    price: 12.75,
    category: 'Sky Shots / Aerials',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'fancy rocket',
    rating: 4.4,
    stock: 45,
  },
  {
    id: 'sky_bomb_rocket',
    name: 'Bomb Rocket',
    description: 'Powerful rocket culminating in a loud burst.',
    price: 11.00,
    category: 'Sky Shots / Aerials',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'bomb rocket',
    rating: 4.5,
    stock: 50,
  },
  {
    id: 'sky_flower_pots_shot',
    name: 'Flower Pots Shot',
    description: 'Aerial display that showers down like blooming flower pots.',
    price: 14.20,
    category: 'Sky Shots / Aerials',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'flower pots',
    rating: 4.2,
    stock: 35,
  },
  {
    id: 'sky_colour_bubbles',
    name: 'Colour Bubbles',
    description: 'Produces an array of colorful bubbling effects in the sky.',
    price: 10.50,
    category: 'Sky Shots / Aerials',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'color bubbles',
    rating: 4.1,
    stock: 55,
  },
  {
    id: 'sky_sky_king',
    name: 'Sky King',
    description: 'A majestic aerial firework ruling the night sky.',
    price: 25.00,
    category: 'Sky Shots / Aerials',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'king fireworks',
    rating: 4.8,
    stock: 20,
  },

  // Ground Crackers
  {
    id: 'ground_lakshmi_1sound',
    name: 'Lakshmi Crackers (1 sound)',
    description: 'Traditional Lakshmi cracker with a single loud bang.',
    price: 4.50,
    category: 'Ground Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'lakshmi cracker',
    rating: 4.0,
    stock: 150,
  },
  {
    id: 'ground_lakshmi_2sound',
    name: 'Lakshmi Crackers (2 sound)',
    description: 'Traditional Lakshmi cracker with two successive loud bangs.',
    price: 5.50,
    category: 'Ground Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'lakshmi cracker',
    rating: 4.2,
    stock: 120,
  },
  {
    id: 'ground_lakshmi_3sound',
    name: 'Lakshmi Crackers (3 sound)',
    description: 'Traditional Lakshmi cracker with three successive loud bangs.',
    price: 6.50,
    category: 'Ground Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'lakshmi cracker',
    rating: 4.3,
    stock: 100,
  },
  {
    id: 'ground_deluxe_lakshmi',
    name: 'Deluxe Lakshmi',
    description: 'A premium version of the classic Lakshmi cracker.',
    price: 7.00,
    category: 'Ground Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'deluxe cracker',
    rating: 4.5,
    stock: 80,
  },
  {
    id: 'ground_bijili_crackers',
    name: 'Bijili Crackers',
    description: 'Small, quick, and sharp sounding crackers.',
    price: 3.00,
    category: 'Ground Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'bijili crackers',
    rating: 3.9,
    stock: 200,
  },
  {
    id: 'ground_atom_bomb',
    name: 'Atom Bomb',
    description: 'Very loud ground cracker known for its powerful burst.',
    price: 4.99,
    category: 'Ground Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'atom bomb',
    rating: 4.7,
    stock: 100,
  },
  {
    id: 'ground_rasi_bomb',
    name: 'Rasi Bomb',
    description: 'A popular and reliable loud ground cracker.',
    price: 4.25,
    category: 'Ground Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'rasi bomb',
    rating: 4.1,
    stock: 130,
  },
  {
    id: 'ground_big_bomb_chakkaram',
    name: 'Big Bomb / Chakkaram Bomb',
    description: 'A combination of a loud bomb and a spinning chakkaram effect.',
    price: 8.00,
    category: 'Ground Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'bomb chakkaram',
    rating: 4.4,
    stock: 70,
  },

  // Sparklers
  {
    id: 'sparkler_colour_6inch',
    name: 'Colour Sparkler (6 inch)',
    description: '6-inch sparklers producing vibrant colored sparks.',
    price: 2.00,
    category: 'Sparklers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'color sparkler',
    rating: 4.0,
    stock: 250,
  },
  {
    id: 'sparkler_colour_10inch',
    name: 'Colour Sparkler (10 inch)',
    description: '10-inch sparklers producing vibrant colored sparks.',
    price: 3.00,
    category: 'Sparklers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'color sparkler',
    rating: 4.2,
    stock: 200,
  },
  {
    id: 'sparkler_colour_12inch',
    name: 'Colour Sparkler (12 inch)',
    description: '12-inch sparklers producing vibrant colored sparks.',
    price: 3.50,
    category: 'Sparklers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'color sparkler',
    rating: 4.3,
    stock: 180,
  },
  {
    id: 'sparkler_gold',
    name: 'Gold Sparkler',
    description: 'Classic sparklers with bright golden sparks.',
    price: 2.50,
    category: 'Sparklers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'gold sparkler',
    rating: 4.1,
    stock: 220,
  },
  {
    id: 'sparkler_electric',
    name: 'Electric Sparkler',
    description: 'Sparklers with a unique crackling electric spark effect.',
    price: 3.20,
    category: 'Sparklers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'electric sparkler',
    rating: 4.4,
    stock: 150,
  },
  {
    id: 'sparkler_crackling',
    name: 'Crackling Sparklers',
    description: 'Sparklers that produce a fun crackling sound with sparks.',
    price: 3.00,
    category: 'Sparklers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'crackling sparkler',
    rating: 4.2,
    stock: 160,
  },

  // Spinning Crackers
  {
    id: 'spinning_chakkaram_ground_wheel',
    name: 'Chakkaram (Ground Wheel)',
    description: 'Classic ground spinning wheel creating a circle of sparks.',
    price: 1.99,
    category: 'Spinning Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'ground wheel',
    rating: 3.9,
    stock: 300,
  },
  {
    id: 'spinning_colour_chakkaram',
    name: 'Colour Chakkaram',
    description: 'Ground spinning wheel that emits multi-colored sparks.',
    price: 2.75,
    category: 'Spinning Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'color chakkaram',
    rating: 4.0,
    stock: 250,
  },
  {
    id: 'spinning_twinkling_wheel',
    name: 'Twinkling Wheel',
    description: 'Spinning wheel that produces a shower of twinkling sparks.',
    price: 3.15,
    category: 'Spinning Crackers',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'twinkling wheel',
    rating: 4.1,
    stock: 220,
  },

  // Fancy / Novelty Crackers
  {
    id: 'novelty_bullet_shell',
    name: 'Bullet Shell',
    description: 'Novelty cracker shaped like a bullet shell with effects.',
    price: 4.00,
    category: 'Fancy / Novelty',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'bullet firework',
    rating: 3.7,
    stock: 100,
  },
  {
    id: 'novelty_cartoon_shot',
    name: 'Cartoon Shot',
    description: 'Fun cracker that ejects cartoon-themed novelties.',
    price: 4.75,
    category: 'Fancy / Novelty',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'cartoon firework',
    rating: 3.9,
    stock: 90,
  },
  {
    id: 'novelty_disco_shot',
    name: 'Disco Shot',
    description: 'Creates a mini disco light effect with colorful sparks.',
    price: 5.50,
    category: 'Fancy / Novelty',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'disco firework',
    rating: 4.0,
    stock: 80,
  },
  {
    id: 'novelty_helicopter_spinner',
    name: 'Helicopter Spinner',
    description: 'Spins and then flies up like a helicopter with sparks.',
    price: 6.00,
    category: 'Fancy / Novelty',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'helicopter firework',
    rating: 4.2,
    stock: 70,
  },
  {
    id: 'novelty_butterflies',
    name: 'Butterflies',
    description: 'Crackers that flutter and fly with colorful light.',
    price: 5.25,
    category: 'Fancy / Novelty',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'butterfly firework',
    rating: 4.1,
    stock: 110,
  },
  {
    id: 'novelty_snake_tablet',
    name: 'Snake Tablet',
    description: 'Classic novelty that produces a growing "snake" of ash.',
    price: 1.50,
    category: 'Fancy / Novelty',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'snake firework',
    rating: 3.5,
    stock: 150,
  },
  {
    id: 'novelty_emoji_bomb',
    name: 'Emoji Bomb',
    description: 'Fun crackers with emoji faces and light effects.',
    price: 4.90,
    category: 'Fancy / Novelty',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'emoji firework',
    rating: 3.8,
    stock: 95,
  },
  {
    id: 'novelty_colour_torch',
    name: 'Colour Torch',
    description: 'Handheld torch emitting bright colored flames/sparks.',
    price: 3.75,
    category: 'Fancy / Novelty',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'color torch',
    rating: 4.0,
    stock: 120,
  },
  {
    id: 'novelty_crackling_balls',
    name: 'Crackling Balls',
    description: 'Small balls that produce a loud crackling sound.',
    price: 2.50,
    category: 'Fancy / Novelty',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'crackling balls',
    rating: 3.9,
    stock: 180,
  },

  // Kids Special
  {
    id: 'kids_magic_pop',
    name: 'Magic Pop (Pop Pop)',
    description: 'Classic throwable snappers that pop on impact.',
    price: 1.00,
    category: 'Kids Special',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'pop snappers',
    rating: 4.5,
    stock: 400,
  },
  {
    id: 'kids_pencil_crackers',
    name: 'Pencil Crackers',
    description: 'Small, safe crackers shaped like pencils.',
    price: 1.75,
    category: 'Kids Special',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'pencil crackers',
    rating: 4.0,
    stock: 300,
  },
  {
    id: 'kids_colour_matches',
    name: 'Colour Matches',
    description: 'Matches that burn with different colored flames.',
    price: 2.00,
    category: 'Kids Special',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'color matches',
    rating: 3.8,
    stock: 250,
  },
  {
    id: 'kids_fountain_pen',
    name: 'Fountain Pen',
    description: 'Novelty firework shaped like a pen, emitting sparks.',
    price: 3.00,
    category: 'Kids Special',
    imageUrl: 'https://placehold.co/400x300.png',
    imageHint: 'pen firework',
    rating: 3.9,
    stock: 200,
  },
];

export const getProductById = (id: string): Product | undefined => {
  return products.find(p => p.id === id);
};

export const getProductsByCategory = (categorySlug: string): Product[] => {
  const category = categories.find(c => c.slug === categorySlug);
  if (!category) return [];
  return products.filter(p => p.category === category.name);
};


    
